// {
//  id: "ghi",
//  name: "Gettó Gulyás",
//  lat: 47.49791,
//  lng: 19.05468,
//  address: "Wesselényi u. 18, 1077 Budapest",
//  contact: "+36 1 786 5087",
//  website: "https://www.gettogulyas.hu",
//  kitchen: "Traditional Hungarian with a modern twist",
//  type: "Rustic restaurant with a casual vibe",
//  tags: ["up-scale", "traditional", "modern", "family friendly"],
//  menu: {
//    Monday: {
//      description: "Goulash Soup + Beef Stew with Dumplings",
//      price: "2390 Ft",
//      dessert: "Strudel",
//      dessertPrice: "810 Ft",
//      tags: ["beef", "dumplings", "traditional", "rich"],
//    },
//    Tuesday: {
//      description: "Chicken Paprikash + Noodles with Sour Cream",
//      price: "2390 Ft",
//      dessert: "Hungarian Pancake",
//      dessertPrice: "810 Ft",
//      tags: ["chicken", "paprikash", "comfort food", "Hungarian classic"],
//    },
//    Wednesday: {
//      description: "Fish Soup + Grilled Pork with Cabbage",
//      price: "2390 Ft",
//      dessert: "Chestnut Puree",
//      dessertPrice: "810 Ft",
//      tags: ["pork", "fish", "grilled", "traditional"],
//    },
//    Thursday: {
//      description: "Vegetable Stew + Sausages",
//      price: "2390 Ft",
//      dessert: "Somlói Galuska",
//      dessertPrice: "810 Ft",
//      tags: ["vegetarian", "hearty", "sausage", "Hungarian classic"],
//    },
//    Friday: {
//      description: "Tomato Soup + Grilled Trout",
//      price: "2390 Ft",
//      dessert: "Apple Strudel",
//      dessertPrice: "810 Ft",
//      tags: ["seafood", "light", "grilled", "traditional"],
//    },
//  },
//  rating: 4.6,
//  reviews: [
//    {
//      user: "Emma W.",
//      rating: 5,
//      review: "Gettó Gulyás is a must-visit for anyone wanting authentic Hungarian cuisine. The goulash soup was the best I've had in Budapest, and the atmosphere is cozy and inviting. The staff were friendly and attentive. I'll be coming back for sure!",
//      date: "2024-01-20",
//    },
//    {
//      user: "Peter D.",
//      rating: 4,
//      review: "Really enjoyed my meal here! The chicken paprikash was delicious, and the noodles were cooked perfectly. The only downside was that it took a little while for our food to arrive, but it was worth the wait.",
//      date: "2024-02-12",
//    },
//    {
//      user: "Julia M.",
//      rating: 4,
//      review: "Great place with a fun vibe! I loved the grilled pork, which was tender and flavorful. The dumplings were a nice touch as well. I would recommend this spot to anyone looking for hearty Hungarian food.",
//      date: "2024-03-10",
//    },
//    {
//      user: "Mark L.",
//      rating: 3,
//      review: "The restaurant has a nice atmosphere, but my experience was just okay. The food was good but not exceptional. I had the fish soup, which was decent but lacked depth in flavor.",
//      date: "2024-03-29",
//    },
//    {
//      user: "Sarah H.",
//      rating: 5,
//      review: "One of the best dining experiences I've had! The trout was grilled to perfection, and the strudel was the perfect finish. The service was outstanding, and the cozy ambiance made it even better. Highly recommend!",
//      date: "2024-04-12",
//    },
//  ],
// },