const Locations = [
  {
    id: "abc",
    name: "Budapest Jazz Club",
    lat: 47.51374,
    lng: 19.04976,
    address: "Hollán Ernő u. 7, 1136 Budapest",
    contact: "+36 1 789 9939",
    website: "https://www.bjc.hu",
    kitchen: "Traditional Hungarian",
    type: "Jazz club with a cozy and relaxed atmosphere",
    tags: ["authentic", "homey", "cosy"],
    menu: {
      Monday: {
        description: "Goulash Soup + Beef Stew with Mashed Potatoes",
        price: "2490 Ft",
        dessert: "Apple Pie",
        dessertPrice: "810 Ft",
        tags: ["traditional", "hearty", "beef", "soup"],
      },
      Tuesday: {
        description: "Chicken Paprikash + Noodles with Cottage Cheese",
        price: "2490 Ft",
        dessert: "Chocolate Cake",
        dessertPrice: "810 Ft",
        tags: ["chicken", "noodles", "traditional", "comfort food"],
      },
      Wednesday: {
        description: "Fish Soup + Roasted Duck with Red Cabbage",
        price: "2490 Ft",
        dessert: "Somlói Galuska",
        dessertPrice: "810 Ft",
        tags: ["fish", "duck", "rich", "Hungarian classic"],
      },
      Thursday: {
        description: "Vegetable Stew + Pork Schnitzel",
        price: "2490 Ft",
        dessert: "Vanilla Ice Cream",
        dessertPrice: "810 Ft",
        tags: ["vegetarian", "pork", "fried", "comfort food"],
      },
      Friday: {
        description: "Tomato Soup + Grilled Salmon",
        price: "2490 Ft",
        dessert: "Chestnut Puree",
        dessertPrice: "810 Ft",
        tags: ["seafood", "healthy", "light", "grilled"],
      },
    },
    rating: 4.5,
    reviews: [
      {
        user: "Anna K.",
        rating: 5,
        review: "The atmosphere at Budapest Jazz Club is simply enchanting. The live jazz music combined with a cozy setting makes for an unforgettable experience. The food was delicious and the service attentive, making it a perfect night out.",
        date: "2024-01-15",
      },
      {
        user: "Mark T.",
        rating: 4,
        review: "I had a wonderful time at the Jazz Club. The Goulash Soup was a highlight of my meal, and the ambiance created by the musicians was fantastic. It can get crowded, but it adds to the lively feel of the place.",
        date: "2024-02-10",
      },
      {
        user: "Sofia L.",
        rating: 4,
        review: "The food was good, but I was particularly impressed by the live performances. It's great to enjoy good food while listening to talented musicians. A lovely way to spend an evening with friends.",
        date: "2024-03-05",
      },
      {
        user: "John R.",
        rating: 3,
        review: "Overall, it was a decent experience. The service was a bit slow, but the food was hearty. The jazz music added a nice touch, and I would give it another try during a less busy night.",
        date: "2024-03-25",
      },
      {
        user: "Lara S.",
        rating: 5,
        review: "Absolutely loved the atmosphere! The Jazz Club is my new favorite spot in Budapest. The combination of amazing food and live jazz makes for a unique dining experience that I can't wait to repeat.",
        date: "2024-04-10",
      },
    ],
  },
  {
    id: "def",
    name: "Cafe Vian",
    lat: 47.50644,
    lng: 19.05866,
    address: "Liszt Ferenc tér 9, 1061 Budapest",
    contact: "+36 1 413 0303",
    website: "https://www.cafevian.com",
    kitchen: "French-inspired European cuisine",
    type: "Elegant café and restaurant",
    tags: ["up-scale", "traditional", "modern", "family friendly", "barbeque"],
    menu: {
      Monday: {
        description: "French Onion Soup + Duck Breast with Mashed Potatoes",
        price: "2590 Ft",
        dessert: "Crème Brûlée",
        dessertPrice: "910 Ft",
        tags: ["french", "duck", "creamy", "gourmet"],
      },
      Tuesday: {
        description: "Caesar Salad + Grilled Chicken Breast",
        price: "2590 Ft",
        dessert: "Fruit Tart",
        dessertPrice: "910 Ft",
        tags: ["healthy", "chicken", "light", "salad"],
      },
      Wednesday: {
        description: "Mushroom Soup + Beef Bourguignon",
        price: "2590 Ft",
        dessert: "Cheesecake",
        dessertPrice: "910 Ft",
        tags: ["beef", "french classic", "hearty", "slow-cooked"],
      },
      Thursday: {
        description: "Tomato Soup + Grilled Lamb Chops",
        price: "2590 Ft",
        dessert: "Chocolate Soufflé",
        dessertPrice: "910 Ft",
        tags: ["lamb", "grilled", "rich", "gourmet"],
      },
      Friday: {
        description: "Leek Soup + Grilled Salmon",
        price: "2590 Ft",
        dessert: "Lemon Sorbet",
        dessertPrice: "910 Ft",
        tags: ["seafood", "light", "healthy", "grilled"],
      },
    },
    rating: 4.7,
    reviews: [
      {
        user: "James P.",
        rating: 5,
        review: "Cafe Vian offers a delightful dining experience. The ambiance is chic and welcoming, and the menu is filled with exquisite choices. The French Onion Soup was superb, and the Crème Brûlée was to die for. Highly recommended!",
        date: "2024-02-01",
      },
      {
        user: "Claire B.",
        rating: 4,
        review: "I enjoyed my lunch here. The grilled chicken salad was fresh and satisfying, and the atmosphere was perfect for a midday break. I'll definitely return to try more of their menu.",
        date: "2024-02-20",
      },
      {
        user: "Daniel C.",
        rating: 4,
        review: "Very nice cafe with a great selection of dishes. The beef bourguignon was rich and flavorful. My only critique is that the service could be a bit quicker, but overall a lovely experience.",
        date: "2024-03-15",
      },
      {
        user: "Rebecca F.",
        rating: 5,
        review: "Absolutely loved it! The tomato soup was delicious, and the lamb chops were perfectly cooked. The dessert menu is exquisite. I can't wait to come back and try more!",
        date: "2024-04-05",
      },
      {
        user: "Lucas N.",
        rating: 3,
        review: "It was a decent experience, but I expected a bit more from the food based on the reviews. While the atmosphere is great, I felt the flavors could have been stronger.",
        date: "2024-04-15",
      },
    ],
  },
  {
    id: "ghi",
    name: "Gettó Gulyás",
    lat: 47.49791,
    lng: 19.05468,
    address: "Wesselényi u. 18, 1077 Budapest",
    contact: "+36 1 786 5087",
    website: "https://www.gettogulyas.hu",
    kitchen: "Traditional Hungarian with a modern twist",
    type: "Rustic restaurant with a casual vibe",
    tags: ["up-scale", "traditional", "modern", "family friendly"],
    menu: {
      Monday: {
        description: "Goulash Soup + Beef Stew with Dumplings",
        price: "2390 Ft",
        dessert: "Strudel",
        dessertPrice: "810 Ft",
        tags: ["beef", "dumplings", "traditional", "rich"],
      },
      Tuesday: {
        description: "Chicken Paprikash + Noodles with Sour Cream",
        price: "2390 Ft",
        dessert: "Hungarian Pancake",
        dessertPrice: "810 Ft",
        tags: ["chicken", "paprikash", "comfort food", "Hungarian classic"],
      },
      Wednesday: {
        description: "Fish Soup + Grilled Pork with Cabbage",
        price: "2390 Ft",
        dessert: "Chestnut Puree",
        dessertPrice: "810 Ft",
        tags: ["pork", "fish", "grilled", "traditional"],
      },
      Thursday: {
        description: "Vegetable Stew + Sausages",
        price: "2390 Ft",
        dessert: "Somlói Galuska",
        dessertPrice: "810 Ft",
        tags: ["vegetarian", "hearty", "sausage", "Hungarian classic"],
      },
      Friday: {
        description: "Tomato Soup + Grilled Trout",
        price: "2390 Ft",
        dessert: "Apple Strudel",
        dessertPrice: "810 Ft",
        tags: ["seafood", "light", "grilled", "traditional"],
      },
    },
    rating: 4.6,
    reviews: [
      {
        user: "Emma W.",
        rating: 5,
        review: "Gettó Gulyás is a must-visit for anyone wanting authentic Hungarian cuisine. The goulash soup was the best I've had in Budapest, and the atmosphere is cozy and inviting. The staff were friendly and attentive. I'll be coming back for sure!",
        date: "2024-01-20",
      },
      {
        user: "Peter D.",
        rating: 4,
        review: "Really enjoyed my meal here! The chicken paprikash was delicious, and the noodles were cooked perfectly. The only downside was that it took a little while for our food to arrive, but it was worth the wait.",
        date: "2024-02-12",
      },
      {
        user: "Julia M.",
        rating: 4,
        review: "Great place with a fun vibe! I loved the grilled pork, which was tender and flavorful. The dumplings were a nice touch as well. I would recommend this spot to anyone looking for hearty Hungarian food.",
        date: "2024-03-10",
      },
      {
        user: "Mark L.",
        rating: 3,
        review: "The restaurant has a nice atmosphere, but my experience was just okay. The food was good but not exceptional. I had the fish soup, which was decent but lacked depth in flavor.",
        date: "2024-03-29",
      },
      {
        user: "Sarah H.",
        rating: 5,
        review: "One of the best dining experiences I've had! The trout was grilled to perfection, and the strudel was the perfect finish. The service was outstanding, and the cozy ambiance made it even better. Highly recommend!",
        date: "2024-04-12",
      },
    ],
  },
];

export default Locations;